server:
  port: 8081

spring:
  application:
    name: customer-service

  data:
    mongodb:
      uri: mongodb://host.docker.internal:27017/db_customer

  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: false

logging:
  level:
    root: INFO
    com.bank.customer: DEBUG